import { RefineKbarProvider } from "@refinedev/kbar";
import { RefineSnackbarProvider } from "@refinedev/mui";
import { Metadata } from "next";
// import { cookies } from "next/headers";
import { ColorModeContextProvider } from "@contexts/color-mode";
import React, { Suspense } from "react";
import "react-multi-carousel/lib/styles.css";
import App from ".";
import "../index.css";

export const metadata: Metadata = {
  title: "Dapp store",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = typeof window !== "undefined" && localStorage.getItem("theme");
  const defaultMode = theme === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <App>{children}</App>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
